spring.application.name=studyplanner

spring.datasource.url=jdbc:postgresql://localhost:5432/studyplanner
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=c3R1ZHktcGxhbm5lci1zZWNyZXQta2V5LXBhcmEtZGVzZW52b2x2aW1lbnRvLTEyMzQ1Njc4OTA=
jwt.expiration=86400000

server.port=8080